export const API_URL = 'https://manuais-hp.onrender.com/chat';

export const MANUALS = [
  {
    id: 'e52645_guia',
    label: 'E52645',
    subtitle: 'Guia do Usuario',
    color: '#00d4aa',
    indexKey: 'e52645_guia',
    tags: ['E52645','MFP','Flow'],
    topics: {
      'Operacao': ['Como carregar papel nas bandejas?','Como imprimir frente e verso?','Como digitalizar para e-mail?','Como usar o grampeador?'],
      'Suprimentos': ['Como substituir o cartucho de toner?','Numero de peca do cartucho?','Substituir cartucho de grampos'],
      'Rede': ['Como configurar o IP?','Como acessar o EWS?','Digitalizar para Pasta de Rede'],
      'Problemas': ['Como resolver atolamentos?','Problemas de qualidade de impressao','Fax nao funciona','USB nao responde'],
    },
    prompt: 'Voce e especialista na HP LaserJet Managed MFP E52645. Use os TRECHOS DO MANUAL abaixo para responder. Se a resposta estiver nos trechos, responda com base neles. Se nao estiver, diga claramente e busque na internet. Idioma: Portugues Brasileiro.',
  },
  {
    id: 'm501_catalog',
    label: 'M501/506/507',
    subtitle: 'Service Parts',
    color: '#0096ff',
    indexKey: 'service',
    tags: ['M501','M506','M507'],
    topics: {
      'Pecas': ['Pecas disponiveis para o M501?','Numero de peca do fusor M506?','Componentes da bandeja'],
      'Service': ['Reparo do M507','Diagnostico de falhas','Teoria de operacao'],
      'Substituicao': ['Como trocar o fusor?','Rolo de transferencia','Placa formatadora'],
    },
    prompt: 'Voce e especialista em service HP LaserJet M501/M506/M507. Use os TRECHOS DO MANUAL abaixo. Se nao encontrar, diga e busque online. Responda em Portugues Brasileiro.',
  },
  {
    id: 'm527_catalog',
    label: 'M527/M528',
    subtitle: 'Service Parts',
    color: '#0096ff',
    indexKey: 'service',
    tags: ['M527','M528'],
    topics: {
      'Pecas': ['Pecas do ADF M527','Componentes do scanner M528','Conjunto de digitalizacao'],
      'Service': ['Diagnostico do ADF','Calibracao do scanner','Vidro de digitalizacao'],
      'Substituicao': ['Separacao do ADF','Rolo de puxada','Placa de controle'],
    },
    prompt: 'Voce e especialista em service HP LaserJet MFP M527/M528. Use os TRECHOS DO MANUAL abaixo. Se nao encontrar, diga e busque online. Responda em Portugues Brasileiro.',
  },
  {
    id: 'e50045_catalog',
    label: 'E50045/145',
    subtitle: 'Service Parts',
    color: '#0096ff',
    indexKey: 'service',
    tags: ['E50045','E50145'],
    topics: {
      'Pecas': ['Pecas do E50045','Part numbers E50145','Fusor gerenciado'],
      'Service': ['Diagnostico E50045','Motor laser','Problemas eletricos'],
      'Substituicao': ['Rolo de transferencia','Cartucho de imagem','Bandejas alta capacidade'],
    },
    prompt: 'Voce e especialista em service HP LaserJet Managed E50045/E50145. Use os TRECHOS DO MANUAL abaixo. Se nao encontrar, diga e busque online. Responda em Portugues Brasileiro.',
  },
  {
    id: 'e52545_catalog',
    label: 'E52545/645',
    subtitle: 'Service Parts',
    color: '#0096ff',
    indexKey: 'service',
    tags: ['E52545','E52645'],
    topics: {
      'Pecas': ['Pecas MFP E52645','Part numbers ADF E52545','Fusor MFP'],
      'Service': ['Diagnostico MFP E52645','Calibracao scanner','Reparo avancado'],
      'Substituicao': ['Conjunto ADF','Fusor alta capacidade','Placa de controle'],
    },
    prompt: 'Voce e especialista em service HP LaserJet Managed MFP E52545/E52645. Use os TRECHOS DO MANUAL abaixo. Se nao encontrar, diga e busque online. Responda em Portugues Brasileiro.',
  },
  {
    id: 'cpmd',
    label: 'Codigos Erro',
    subtitle: 'CPMD 2023',
    color: '#a855f7',
    indexKey: 'cpmd',
    tags: ['M501','M527','E52645','CPMD'],
    topics: {
      'Suprimentos 10xx': ['Erro 10.xx.xx - suprimento','Memoria do cartucho','Cartucho nao reconhecido'],
      'Atolamentos 13xx': ['Erro 13.xx.xx - atolamento','Atolamento no ADF','Atolamento no fusor'],
      'Firmware 4xxx': ['Erro 49.xx.xx firmware','Erro 41.03 misprint','Erro 50.xx fusor'],
      'Painel': ['Checking engine','Output Bin Full','NON HP Supply Installed'],
    },
    prompt: 'Voce e especialista em codigos de erro HP LaserJet (CPMD 2023). Use os TRECHOS DO MANUAL abaixo para identificar o erro e os passos de solucao. Se nao encontrar, diga e busque online. Responda em Portugues Brasileiro.',
  },
];
